### PR TITLE
Rewrite for grunt 0.4

### PR DESCRIPTION
**Pull request by ghost**
I rewrote the main task for grunt 0.4. The plugin is working fine for me now. This should fix issues #1 and #2.

I also added the possibility to specify a base file distinct from the file that the templates should be inlined into (e.g. in my use case, where the base file is `app/index.html` while the templates are actually inlined into `dist/index.html`).

### CODE REVIEW

**Comment by rahim** [comment]
I just hit the compatibility issue myself, would be great to see this merged and a new release tag cut.

**Comment by marekhrabe** [comment]
What's the status of this pull-request? I'm using version from @anim for weeks and everything works perfectly.
Is there any issue that prevents you from merge?

**Comment by ghost** [comment]
@marekhrabe, have a look at https://github.com/ericclemmons/grunt-angular-templates. I'm currently not using this, but it might be a better (actively maintained) alternative.

**Comment by nebhale** [comment]
Sorry about that everyone.  I don't use Grunt much these days and didn't notice the PR.

**Comment by marekhrabe** [comment]
Thanks a lot fo merge :) I like the approach of having templates in html more than in templateCache

**Pull request merged**
